server:
  port: 12000
spring:
  application:
    name: IronBirch-eureka
eureka:
  instance:
    hostname: IronBirchEureka
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:12000/eureka
